name: BuildingAndTestWorkflow.yml
on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java Project
        uses: ./.github/actions/setup-java-project
      - name: Run Checkstyle
        run: mvn checkstyle:check
