name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      project-type:
        required: true
        type: string
      task:
        required: true
        type: string
      java-version:
        required: false
        type: string
        default: '21'
      node-version:
        required: false
        type: string
        default: '20'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Test Task
        uses: ./.github/actions/setup-java-project
        with:
          project-type: ${{ inputs.project-type }}
          task: ${{ inputs.task }}
          java-version: ${{ inputs.java-version }}
          node-version: ${{ inputs.node-version }}